#!/usr/bin/env bash

# Lock screen with Gruvbox colors
i3lock-color \
  -i ~/git/nix-config/assets/wallpaper-gibson-blur.png \
  --insidever-color=D7992180 \
  --ringver-color=D79921FF \
  \
  --insidewrong-color=cc241d80 \
  --ringwrong-color=cc241dFF \
  \
  --inside-color=1d202180 \
  --ring-color=98971aFF \
  --line-color=d79921FF \
  --separator-color=d79921FF \
  \
  --verif-color=458588FF \
  --wrong-color=cc241dFF \
  --keyhl-color=458588FF \
  --bshl-color=b16286FF \
  --time-color=b16286FF \
  --date-color=b16286FF \
  --layout-color=ebdbb2FF \
  --ring-width=12 \
  --radius=120 \
  \
  --clock \
  --indicator \
  --date-pos="w/2:h-150" \
  --date-font="Fira Sans" \
  --date-size=48 \
  --time-pos="w/2:h-250" \
  --time-font="Fira Code" \
  --time-size=100 \
  --time-str="%H:%M:%S" \
  --date-str="%A, %m-%d-%Y"